# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ded9a3a9ba2be48cda5f474dbb0673f0cceb28d626512c500d6bfda7ad9e8bccae1f6b2fa0d8b1820f0183a4098fa3b61641e5808108ce83e2811e96e8d122c

test:
  secret_key_base: 53efbea05606729c395a5910a0dbd8909e47e392f5bdbab1f759720d34facab495e0a74e8c597d9359e2c30909817849ac69b110265c7ee64727d95c436931ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
